### ISSUE TITLE
Speedup CI

### ISSUE THREAD

**Issue by greyscaled** [coder/enterprise-images#46]
Right now each push/pr [builds all images](https://github.com/cdr/enterprise-images/blob/98c24a3f55e3a69249f6f9d0921a57bc767d6cc1/.github/workflows/ci.yaml#L26-L31)

However, most of the time we're patching a single image. We may be able to utilize a mechanism that determines which images ought to be built based off of the their base image.

## Example

Changing a [pycharm image](https://github.com/cdr/enterprise-images/tree/master/images/pycharm) should only require that image to be built

Changing a [base image](https://github.com/cdr/enterprise-images/tree/master/images/base) should require all images to be built

**Comment by jawnsy** [comment]
We have a partial solution in #55 by splitting the builds by distro and running them in parallel, which also helps avoid the build servers' disks filling up. However, it's still re-building everything even if nothing in the images changes, so is pretty wasteful.

One challenge is that the builds are not completely reproducible, which is somewhat by design (i.e. when someone pushes an an update to the official `ubuntu`, we have to re-build the `enterprise-base:ubuntu` image)

**Comment by matifali** [comment]
CI is now faster after we started using depot.dev in #243
